const COLORS_NAME = {
  WHITE: '#FFFFFF',
  BLACK: '#000000',
  GRAY: '#E0E0E6',
  ALICE_BLUE: '#EDF9FF',
  WATER_BLUE: '#D6F0FF',
  DIAMOND_BLUE: '#B5E6FF',
  PALE_BLUE: '#83D8FF',
  PICTON_BLUE: '#48C1FF',
  DODGER_BLUE: '#1EA0FF',
  AZURE_BLUE: '#0681FF',
  TRUE_BLUE: '#0061E3',
  SAPPHIRE_BLUE: '#0853C5',
  YALE_BLUE: '#0D499B',
};

const colorConfig = {
  ...{ COLOR_NAME: COLORS_NAME },
  primary: {
    '50': COLORS_NAME.ALICE_BLUE,
    '100': COLORS_NAME.WATER_BLUE,
    '200': COLORS_NAME.DIAMOND_BLUE,
    '300': COLORS_NAME.PALE_BLUE,
    '400': COLORS_NAME.PICTON_BLUE,
    '500': COLORS_NAME.DODGER_BLUE,
    '600': COLORS_NAME.AZURE_BLUE,
    '700': COLORS_NAME.TRUE_BLUE,
    '800': COLORS_NAME.SAPPHIRE_BLUE,
    '900': COLORS_NAME.YALE_BLUE,
  },
  secondary: {},
  neutral: {},
};

export default colorConfig;
